# Housing in Pittsburgh

## Eric Wang

In [4]:
import pandas as pd

house = pd.read_csv("housedata.tsv", sep="\t")
house.head()

,_id,Neighborhood,Sector #,Population (2010),Total # Units (2000),Total # Units (2010),% Occupied Units (2010),% Vacant Units (2010),# Occupied Units (2010),% Owner Occupied Units (2010),...,% Units Built before 1939,Median Home Value (2000),Med. Val. ('00 in '10 Dollars),Median Home Value (2010),% Change Real Value 2000-2010,Median Sale Price (2010),# Sales Counted (2010),Foreclosures (2008),Foreclosures (2010),% of all Housing Units Foreclosed (2010)
0,1,Allegheny Center,3,933,675,"1,052",51.5%,48.5%,535,10.1%,...,1.3%,"$86,500","$109,535","$136,300",24.4%,NaN,0,0,0,0.0%
1,2,Allegheny West,3,462,390,355,74.9%,25.1%,203,18.2%,...,57.4%,"$159,700","$202,228","$123,600",-38.9%,"$309,940",7,0,1,0.3%
2,3,Allentown,6,"2,500","1,505","1,291",80.0%,20.0%,953,59.2%,...,62.9%,"$34,300","$43,434","$42,200",-2.8%,"$8,500",70,27,11,0.9%
3,4,Arlington,7,"1,869",880,886,86.6%,13.4%,754,65.4%,...,72.3%,"$38,800","$49,132","$44,200",-10.0%,"$15,397",34,12,13,1.5%
4,5,Arlington Heights,7,244,557,148,91.2%,8.8%,139,18.7%,...,9.2%,"$45,000","$56,984","$64,400",13.0%,NaN,0,0,0,0.0%

In [10]:
import pandas as pd

# Load the dataset
file_path = 'housedata.tsv'
data = pd.read_csv(file_path, sep='\t')

# Clean and convert relevant columns for calculations
columns_to_clean = [
    '% Occupied Units (2010)',
    '% Owner Occupied Units (2010)',
    '% of all Housing Units Foreclosed (2010)',
    'Median Home  Value (2010)',
]

for column in columns_to_clean:
    data[column] = (
        data[column]
        .replace({r'[$%,]': ''}, regex=True)
        .astype(float)
    )

# Calculate the score for each neighborhood
data['Score'] = (
    data['% Occupied Units (2010)'] * 0.4 +
    data['% Owner Occupied Units (2010)'] * 0.3 +
    data['Median Home  Value (2010)'] * 0.2 -
    data['% of all Housing Units Foreclosed (2010)'] * 0.1
)

# Sort the neighborhoods by score in descending order
sorted_data = data.sort_values('Score', ascending=False)


pd.set_option('display.max_rows', None)  # Display all rows
pd.set_option('display.max_columns', None)  # Display all columns

print(sorted_data[['Neighborhood', 'Score']])  # Displays the top neighborhoods

                 Neighborhood     Score
75        Squirrel Hill North  69034.94
55              North Oakland  54646.57
67                  Shadyside  53018.17
62               Point Breeze  48121.75
76        Squirrel Hill South  40331.52
65              Regent Square  39320.72
39              Highland Park  33532.72
33                 Friendship  33500.97
79             Strip District  32404.76
71           South Side Flats  30797.91
19            Central Oakland  28911.82
0            Allegheny Center  27283.63
16  Central Business District  25199.73
18          Central Northside  24905.27
1              Allegheny West  24755.39
54              New Homestead  23544.61
14       California-Kirkbride  22684.91
5                  Banksville  22233.11
81             Swisshelm Park  21784.59
58                    Oakwood  21751.30
48                 Manchester  20308.16
24           Duquesne Heights  20152.19
63         Point Breeze North  19947.41
23           Crawford-Roberts  18963.69
80                Summer Hill  18937.13
88                   Westwood  18800.97
9                  Bloomfield  18614.59
36                 Greenfield  18236.43
66                  Ridgemont  18161.25
51                Morningside  17997.18
78            Stanton Heights  17402.29
13                  Brookline  16489.65
12           Brighton Heights  16342.29
6           Bedford Dwellings  16257.19
89                    Windgap  15704.58
52           Mount Washington  15684.52
45              Lincoln Place  15603.49
69              South Oakland  15488.72
25             East Allegheny  15464.18
20             Chartiers City  15403.01
22            Crafton Heights  15384.14
60                Perry North  15317.65
59                  Overbrook  15303.62
72          South Side Slopes  14661.72
31                  Fairywood  14608.34
50                Middle Hill  14606.09
7                   Beechview  14533.23
11                    Bon Air  13963.01
15                    Carrick  13435.70
17      Central Lawrenceville  13419.08
84                 Upper Hill  13315.29
38                  Hazelwood  13157.01
28               East Liberty  12971.14
4           Arlington Heights  12922.09
26              East Carnegie  12757.17
64                Polish Hill  12589.51
49         Marshall-Shadeland  12430.88
68                   Sheraden  12373.39
87               West Oakland  12266.11
34                   Garfield  12104.69
82            Terrace Village  11894.48
74      Spring Hill-City View  11829.86
32                   Fineview  11828.66
47        Lower Lawrenceville  11423.14
53                 Mt. Oliver  11391.91
83                  Troy Hill  10570.26
30                     Esplen  10330.40
61                Perry South  10314.61
29                    Elliott  10310.54
37                       Hays  10216.49
85        Upper Lawrenceville   9790.53
41             Homewood South   9722.25
73              Spring Garden   9644.90
3                   Arlington   8894.11
46   Lincoln-Lemington-Belmar   8804.28
2                   Allentown   8489.67
77                  St. Clair   8252.38
27                 East Hills   8189.85
43                  Knoxville   8031.08
8                 Beltzhoover   7251.35
40             Homewood North   7130.78
44                    Larimer   7015.50
42              Homewood West   6939.68
86                   West End   5999.49
10                      Bluff   4280.21
21                    Chateau       NaN
35                 Glen Hazel       NaN
56                North Shore       NaN
57          Northview Heights       NaN
70                South Shore       NaN

Conclusion:
When creating the dataset I decided to make a point system to determine which neighborhood had the best housing. Based off of the scores given, Squirrel Hill North is the best place for housing in Pittsburgh. In comparison, our favorite, North Shore, is one of the worst neighborhoods for housing. North Shore scored really low and has lots of apartments instead of houses. There was also not enough data on North Shore to be able to determine whether or not North Shore has bad or good housing.